name: build

on:
  push:
    branches: ['master']
    tags: ['v*']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    tags: ['dependencies']
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=test_dir::test
          echo ::set-output name=test_reports_dir::build/test-reports
          echo ::set-output name=test_reports_format::junit

      - name: Run tests
        run: |
          chmod +x batsw
          ./batsw "${{ steps.prep.outputs.test_dir }}" \
            --report-formatter "${{ steps.prep.outputs.test_reports_format }}" \
            --output "${{ steps.prep.outputs.test_reports_dir }}"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-reports
          if-no-files-found: error
          path: ${{ steps.prep.outputs.test_reports_dir }}/*.xml

  release-draft:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Draft release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          body_path: CHANGELOG.md
          files: recordr.sh
          token: ${{ secrets.GITHUB_TOKEN }}
