name: docs

on:
  push:
    branches: ['master']
    tags: ['v*']
    paths-ignore: ['**.md']
  pull_request:
    branches: ['master']
    tags: ['dependencies']
    paths-ignore: ['**.md']
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}--docs
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=recordr_branch::"${{ github.ref_name }}--docs"

      - name: Checkout
        uses: actions/checkout@v2

      - name: ‚óè REC
        if: github.event_name != 'pull_request'
        id: recordr
        uses: ./
        with:
          branch: ${{ steps.prep.outputs.recordr_branch }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        if: startsWith(github.ref, 'refs/heads/')
        with:
          commit-message: |
            ${{ github.workflow }}(docs): update ${{ steps.recordr.outputs.file-list }}
          title: |
            ${{ github.workflow }}(docs): update ${{ steps.recordr.outputs.file-list }}
          body: |
            Updates ${{ steps.recordr.outputs.file-list }}
            ${{ steps.recordr.outputs.markdown }}
          labels: recordr,docs,rec
          branch: ${{ steps.prep.outputs.recordr_branch }}
